languaje: node_js

node_js:
  - "8"
  - "10"
  - "12"
  - "stable"

cache:
  directories:
    - node_modules

matrix:
  include:
    - node_js: "8"
    - node_js: "10"
    - node_js: "12"
    - node_js: "stable"

install:
  - npm install

env:
  global:
    - NODE_ENV=test
    - PORT=3000

script:
  - npm run test

# after_script:
#   - npm run afterScript
