require('module-alias/register');
require('dotenv').config();

const express = require('express');
const cors = require('cors');
const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const { msg } = require('@/lib/messages');

const { routes } = require('@/routes/index');

const { env } = process;

const {
  PORT: port,
  NODE_ENV: nodeEnv,
} = env;

const app = express();

// const corsOptions = require('@/etc/corsConfig');
const { connectDB: db } = require('@/etc/dbConfig');

db();

const {
  log,
  loggerError: errors,
  loggerAccess: access,
} = require('@/etc/logConfig');

app.use(cors());
app.use(errors);
app.use(access);
app.use(express.urlencoded({ extended: false }));
app.use(express.json());
app.use('/api', routes);

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['@/routes/*.js'],
};

const specs = swaggerJsdoc(options);

app.use('/docs', swaggerUi.serve, swaggerUi.setup(specs));

app.listen(port || 3000, () => {
  log().info(msg.server, port, nodeEnv);
});

module.exports = app;
